### ISSUE TITLE
Preprint v2 Comments

### ISSUE THREAD

**Issue by jfy133** [apeltzer/eager2-paper#52]
All points when ticked off means they've been corrected in James' branch and will merged in the future

From Maxime:

- [x] strip_fastq is now renamed, should also be in the manuscript
- [x] Is it really necessary to report all three real 	sys 	user runtime in table 2 ?

**Comment by jfy133** [comment]
- [x] Add Betsy and Maria to acknowledgements

**Comment by JudithNeukamm** [comment]
Some additional comments: 

- [x] The terms 'Fig.' and 'Figure' are mixed up. Should be consistent
- [x] Section Updated Workflow: Comma is missing after ANGSD [63]: 
Genotyping and Consensus Sequence Generation: GATK [57], ANGSD [63] VCF2Genome [39] 
- [x] If a table is referenced, the 'Tab. / Table' is missing in some cases:
... and a tabular comparison of functionality between EAGER, paleomix and nf-core/eager in **1**. 
... Mapping results across all pipelines showed very similar values, with low variation across replicates as can be seen in **3**.
- [x] Section 'Dual Screening of Human and Microbial Pathogen DNA':
In the box with the Nextflow command, you wrote --dedupper markduplicates \. In all other boxes, you specified this option with quotes: --dedupper 'markduplicates' \. What's correct?

**Comment by jfy133** [comment]
From Aida

- [x] Found small typo in methods -> Installation: Quick Start is written as QuickStart

**Comment by jfy133** [comment]
From Zandra:

I'm too tired to figure out how to leave comments on the eager paper in GitHub, so here you go:
## Abstract
- [x] No need to shorten aDNA in abstract since short form is not used
- [x] 'Redesigned' from what?
## Intro
- [x] Ecology is a branch of biology (doesn't make sense to list them separately)
- [x] Maybe isn't good to write "most recently, ancient ‘chewing gum’" since by the time of publication it might not be most recent
- [x] I really dislike writing "Cytosine to Thymine" with capital first letters, it's not proper nomenclature
- [x] The sentence starting "These two pipelines take a similar approach..." is >5 lines long
- [x] "newly named pipeline" should maybe be "renamed pipeline"? I read it as we have named the pipeline recently.
- [x] "best-practises in software development" should be best-practices (practise is the verb, practice the noun).
## Results and discussion
- [x] "robusticity checks" should probably be "robustness checks" (robusticity is more used with robustness of a body)
- [x] You only call it "EAGER v1" once, otherwise it's just EAGER/original EAGER
- [x] Something missing in "...Nextflow’s ability to customise resource settings the parameters..."
- [x] "...partially with PALEOMIX" should be "...partially to PALEOMIX" to match rest of sentence
- [x] "..the optional use as input of a simple table in TSV format" is unnecessarily complicatedly written
- [x] "..putative pathogen detection Ancient metagenomic..." dot missing
- [x] "...with the presence of the Hepatitis B virus" should be "contained Hepatitis B virus" to match beginning of sentence
- [x] "..having a biological sex of Male", please make 'male' lower case. Same in figure legend.
- [x] "Metagenomic hits to both pathogens from the same individuals that yielded complete genomes.." maybe don't mention the complete genomes, it's confusing.
- [x] Fig 2 legend: Some of the bacteria are from soil, not only common oral commensal bacteria. The legend is also very long - maybe the MultiQC release could be in main text?
- [x] Table 2: "PALEOMIX and nf-core/eager has additional" should be "PALEOMIX and nf-core/eager have additional"
- [x] Table 2: Description of column names should be in table legend, not in main text
- [x] Swapping between BWA and bwa through text
