### ISSUE TITLE
Manubot upgrade required to fix broken builds

### ISSUE THREAD

**Issue by dhimmel** [apeltzer/eager2-paper#61]
Greetings Manubot manuscript user. On 2020-11-09, most Manubot manuscripts started encountering errors when building. This does not endanger the existing manuscript, but does make it so changes to the manuscript won't be automatically published by continuous integration.

The error occurs during `pandoc-manubot-cite` filter execution, when panflute detects an incompatible Pandoc version and raises `TypeError: ('invalid api version', [1, 20])`. The issue was triggered when version 2 of panflute was released, which dropped support for older Pandoc versions. We (the Manubot maintainers) had forgotten to pin the panflute dependency, so CI installs the most recent version from [PyPI](https://pypi.org/project/panflute/), which happens to be incompatible. See https://github.com/manubot/rootstock/issues/387 for more information.

The **suggested fix** is to update to the latest version of manubot/rootstock, as described in [SETUP: Merging upstream rootstock changes](https://github.com/manubot/rootstock/blob/master/SETUP.md#merging-upstream-rootstock-changes). We are happy to review upgrade pull requests (just mention it here). In addition, if you are having trouble upgrading, let us know and we can open a pull request to do so.

Upgrading to the current rootstock will also resolve https://github.com/manubot/rootstock/issues/388, which relates to the following message you might have seen in your GitHub Actions CI logs:

> The `set-env` command is deprecated and will be disabled on November 16th.

Thanks for being an early adopter of Manubot!

**Comment by apeltzer** [comment]
Thanks @dhimmel - we'll be looking into the issue and update here. Doesn't sound too difficult to get this working again

**Comment by jfy133** [comment]
@dhimmel we believe the upstream merged worked and GitHub pages apparently successfully deployed. Would be cool that you could check that it looks ok, as we personally didn't see any issues previously.

The githubpages version is at apeltzer.github.io/eager2-paper

**Comment by dhimmel** [comment]
> Would be cool that you could check that it looks ok

Yep looks good. Don't see any problems with the merge commit 9444db7443a66f375c7f2adbffbebb6541b512ea.

Looking at the [CI logs](https://github.com/apeltzer/eager2-paper/runs/1387421453#step:7:41), one of the cited URLs (https://nf-co.re/eager/docs) returns a 404:

```
we have written documentation and tutorials [@url:https://nf-co.re/eager/docs] that also gives guidance on how to run the pipeline
```

But this is a separate issue.

**Comment by jfy133** [comment]
Yeah, that link has changed since we submitted the manuscript so all good from there.

Thanks for checking!
